# Copyright (C) 2008 Dag Odenhall <dag.odenhall@gmail.com>
# Licensed under the Academic Free License version 3.0

if Dir["warp"].empty?
  sh "git clone git://github.com/dag/warp.git"
end

load 'warp/Rakefile'

desc "rsync changes to rubyforge.org"
task :deploy do
  sh "rsync -aCv public/ dag@rubyforge.org:/var/www/gforge-projects/amazing/"
end
