if Dir["warp"].empty?
  sh "git clone git://github.com/dag/warp.git"
end

load 'warp/Rakefile'

desc "rsync changes to rubyforge.org"
task :deploy do
  sh "rsync -aCv public/ dag@rubyforge.org:/var/www/gforge-projects/amazing/"
end
